services:
  doeiy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doeiy-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - PORT=8000
    restart: unless-stopped
