services:
  doeiy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doeiy-app
    ports:
      - "3839:3839"
    volumes:
      - ./app:/app/app
    environment:
      - PORT=3839
    restart: unless-stopped
