version: '3'

tasks:
  build:
    desc: Build the Docker image
    cmds:
    - docker compose build

  build-clean:
    desc: Build the Docker image from scratch without using cache
    cmds:
    - docker compose build --no-cache

  up:
    desc: Start the Docker container in the background
    cmds:
    - docker compose up -d

  down:
    desc: Stop and remove the Docker container
    cmds:
    - docker compose down

  logs:
    desc: View the Docker container logs in real-time
    cmds:
    - docker compose logs -f

  restart:
    desc: Restart the Docker container
    cmds:
    - docker compose restart

  test:
    desc: Run R unit tests inside the Docker container
    cmds:
    - docker compose exec -T doeiy Rscript tests/run_tests.R

  test-clean:
    desc: Rebuild the Docker image without cache and run tests
    cmds:
    - task: build-clean
    - task: up
    - task: test

  check-quality:
    desc: Show summary of codebase quality and testing coverage
    cmds:
    - task: test

  b-M:
    desc: Bump Major version, commit, and tag (e.g., 1.0.1 -> 2.0.0)
    cmds:
    - ./scripts/bump_version.sh major

  b-m:
    desc: Bump minor version, commit, and tag (e.g., 1.0.1 -> 1.1.0)
    cmds:
    - ./scripts/bump_version.sh minor

  b-p:
    desc: Bump patch version, commit, and tag (e.g., 1.0.1 -> 1.0.2)
    cmds:
    - ./scripts/bump_version.sh patch
